
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { 
  Send, 
  Terminal as TerminalIcon, 
  Command, 
  ShieldCheck, 
  AlertTriangle, 
  ExternalLink, 
  ArrowRightLeft, 
  Check, 
  X, 
  FolderOpen, 
  User, 
  Loader2, 
  Globe,
  ListTodo,
  Settings as SettingsIcon,
  Laptop, // New Icon for VSCode Bridge
  // Agent Icons
  MessageSquare,
  Map as MapIcon,
  Cpu,
  Code,
  FlaskConical,
  ShieldAlert,
  Rocket,
  Activity
} from 'lucide-react';
import { AGENTS, AgentMode, Message, ToolState, Task, AppSettings, VirtualFile } from './types';
import { sendMessageToAgent } from './services/aiService';
import { initializeStartupTracking, completeStartup, reportStartupError, setStartupStatusCallback } from './src/utils/StartupTracker';
import { checkOllamaDependencies } from './src/utils/DependencyChecker';
import { SystemMonitor } from './components/SystemMonitor';
import { ToolsPanel } from './components/ToolsPanel';
import { AgentGrid } from './components/AgentGrid';
import { TaskDashboard } from './components/TaskDashboard';
import { SettingsModal } from './components/SettingsModal';
import { IncomingTransmission } from './components/IncomingTransmission';
import { ProjectManager } from './components/ProjectManager'; // Import ProjectManager
import { ConfigurationProvider } from './services/config/configStore';

// Icon Mapping to prevent undefined render errors
const AGENT_ICONS: Record<string, React.ElementType> = {
  'MessageSquare': MessageSquare,
  'Map': MapIcon,
  'Cpu': Cpu,
  'Code': Code,
  'FlaskConical': FlaskConical,
  'ShieldAlert': ShieldAlert,
  'Rocket': Rocket,
  'Activity': Activity
};

// Initial Virtual Files
const INITIAL_FILES: VirtualFile[] = [
  { name: 'package.json', content: '{\n  "name": "nexus-project",\n  "version": "1.0.0"\n}', language: 'json', status: 'unmodified' },
  { name: 'README.md', content: '# Nexus Project\nGenerated by NexusFlow Agents', language: 'markdown', status: 'unmodified' },
  { name: 'src/index.ts', content: 'console.log("Nexus Core Online");', language: 'typescript', status: 'unmodified' },
];

// Helper to cycle enum
const getNextAgent = (current: AgentMode): AgentMode => {
  const agents = Object.values(AgentMode);
  const currentIndex = agents.indexOf(current);
  const nextIndex = (currentIndex + 1) % agents.length;
  return agents[nextIndex];
};

// Helper to infer agent from task title
const inferAgentForTask = (title: string): AgentMode => {
  const lower = title.toLowerCase();
  if (lower.includes('test') || lower.includes('verify')) return AgentMode.TEST;
  if (lower.includes('deploy') || lower.includes('docker') || lower.includes('ci/cd')) return AgentMode.DEPLOY;
  if (lower.includes('design') || lower.includes('architecture')) return AgentMode.ARCHITECT;
  if (lower.includes('monitor') || lower.includes('log')) return AgentMode.MONITOR;
  if (lower.includes('secure') || lower.includes('auth')) return AgentMode.SECURE;
  return AgentMode.CODER; // Default to Coder
};

export default function App() {
  const [activeAgent, setActiveAgent] = useState<AgentMode>(AgentMode.CHAT);
  const [input, setInput] = useState('');
  
  // State: Independent Histories for each Agent (The "Project Folder" Structure)
  const [agentHistories, setAgentHistories] = useState<Record<AgentMode, Message[]>>(() => {
    const initialHistories = {} as Record<AgentMode, Message[]>;
    Object.values(AgentMode).forEach(mode => {
      initialHistories[mode] = mode === AgentMode.CHAT ? [{
        id: 'init',
        role: 'system',
        content: 'NEXUSFLOW CORE ONLINE. PROJECT FOLDER INITIALIZED.',
        timestamp: Date.now(),
        agent: AgentMode.CHAT
      }] : [];
    });
    return initialHistories;
  });

  // Global Tasks State
  const [tasks, setTasks] = useState<Task[]>([]);
  const [showTaskDashboard, setShowTaskDashboard] = useState(false);
  
  // Virtual File System State
  const [virtualFiles, setVirtualFiles] = useState<VirtualFile[]>(INITIAL_FILES);
  const [showProjectManager, setShowProjectManager] = useState(false); // State for VSCode Bridge

  // App Settings
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<AppSettings>({
    suggestionLevel: 'medium',
    soundEnabled: true,
    autoScroll: true,
    animations: true,
    aiProvider: 'gemini',
    ollamaUrl: 'http://localhost:11434',
    ollamaGeneralModel: 'llama3',
    ollamaCodingModel: 'llama3'
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const [showBootSequence, setShowBootSequence] = useState(true);
  const [sidebarTab, setSidebarTab] = useState<'telemetry' | 'tools'>('telemetry');
  
  // Orchestrator State
  const [pendingSwitch, setPendingSwitch] = useState<AgentMode | null>(null);
  const [lastAgentResume, setLastAgentResume] = useState<string>("");
  const [transitionTarget, setTransitionTarget] = useState<AgentMode | null>(null); // For overlay animation

  // Tool State Management
  const [toolState, setToolState] = useState<ToolState>({
    mcp: { active: false, port: '8080' },
    rag: { active: true, content: [] },
    fetch: { active: false, targetUrl: '' },
    doc: { active: false, files: [] }
  });
  
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Startup tracking and dependency checks
  useEffect(() => {
    // Initialize startup tracking
    initializeStartupTracking();

    // Check Ollama dependencies if Ollama is selected
    if (settings.aiProvider === 'ollama') {
      checkOllamaDependencies(settings.ollamaUrl, settings.ollamaGeneralModel, settings.ollamaCodingModel)
        .then((result) => {
          if (result.success) {
            completeStartup();
          } else {
            // Report error with instruction on how to fix
            const errorMsg = `Dependency Check Failed: ${result.message}\n\nAction Steps:\n${result.actionSteps.join('\n')}`;
            reportStartupError(errorMsg);
            console.error('Ollama Dependency Check Failed:', result);
          }
        })
        .catch((error) => {
          console.error('Error checking Ollama dependencies:', error);
          reportStartupError('Failed to verify Ollama dependencies. Please check if Ollama is running and models are available.');
        });
    } else {
      // If not using Ollama, consider startup complete
      setTimeout(completeStartup, 1000); // Small delay for better UX
    }
  }, [settings.aiProvider, settings.ollamaUrl, settings.ollamaGeneralModel, settings.ollamaCodingModel]);

  // Boot animation timer
  useEffect(() => {
    const timer = setTimeout(() => setShowBootSequence(false), 2500);
    return () => clearTimeout(timer);
  }, []);

  // Auto scroll
  useEffect(() => {
    if (settings.autoScroll) {
        messagesEndRef.current?.scrollIntoView({ behavior: 'auto', block: 'end' });
    }
  }, [agentHistories, activeAgent, isProcessing, settings.autoScroll]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Tab') {
        e.preventDefault();
        const next = getNextAgent(activeAgent);
        handleSwitchAgent(next);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [activeAgent]); 

  // Focus input on click
  const handleContainerClick = () => {
    if (!transitionTarget) {
        inputRef.current?.focus();
    }
  };

  /**
   * Generates a "Resume" of the current agent's recent context before switching.
   * This allows the Orchestrator to brief the next agent.
   */
  const handleSwitchAgent = (targetAgent: AgentMode) => {
    if (targetAgent === activeAgent) return;

    // Capture Resume from current agent
    const currentHistory = agentHistories[activeAgent];
    // Take last 5 messages, filter for content
    const recentMessages = currentHistory
        .slice(-5)
        .filter(m => m.role !== 'system')
        .map(m => `[${m.role.toUpperCase()}]: ${m.content}`)
        .join('\n');
    
    if (recentMessages) {
       setLastAgentResume(`PREVIOUS CONTEXT FROM [${AGENTS[activeAgent].name}]:\n${recentMessages}`);
    }

    // Start Visual Transition
    setTransitionTarget(targetAgent);
    
    // Delay the actual state switch to show the animation
    setTimeout(() => {
        setActiveAgent(targetAgent);
        setPendingSwitch(null);
        setTransitionTarget(null);
        
        // Focus input after switch
        setTimeout(() => inputRef.current?.focus(), 50);
    }, 2500); // 2.5 seconds for the "phone call" handshake effect
  };

  // Parse tasks from PLAN agent output
  const extractTasksFromContent = (content: string) => {
     // Regex to find "- [ ] Task" patterns
     const taskRegex = /- \[([ x])\] (.*)/g;
     let match;
     const newTasks: Task[] = [];
     
     while ((match = taskRegex.exec(content)) !== null) {
        const isChecked = match[1] === 'x';
        const title = match[2].trim();
        
        // Avoid duplicates (simple check)
        if (!tasks.some(t => t.title === title)) {
            newTasks.push({
                id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
                title: title,
                status: isChecked ? 'done' : 'idle',
                agent: inferAgentForTask(title)
            });
        }
     }

     if (newTasks.length > 0) {
        setTasks(prev => [...prev, ...newTasks]);
     }
  };

  // Parse Files from CODER/ARCHITECT/TEST outputs
  const extractFilesFromContent = (content: string) => {
    // Regex: FILE: filename.ext \n ```lang \n content \n ```
    // Improved regex handles varied whitespace, bolding, and Windows line endings
    // Matches:
    // 1. "FILE:" or "**FILE:**"
    // 2. Filename (Group 1)
    // 3. Optional whitespace/newlines
    // 4. Code block start ``` + language (Group 2)
    // 5. Content (Group 3)
    // 6. Code block end ```
    const fileRegex = /(?:FILE:|\*\*FILE:\*\*)[ \t]*([^\r\n]+)(?:[\r\n]+\s*)*```(\w*)(?:[\r\n]+)([\s\S]*?)```/g;
    
    let match;
    const newFiles: VirtualFile[] = [];
    
    while ((match = fileRegex.exec(content)) !== null) {
        const fileName = match[1].trim();
        const fileContent = match[3]; // Group 3 is content
        newFiles.push({
            name: fileName,
            content: fileContent,
            language: fileName.split('.').pop() || 'text',
            status: 'new'
        });
    }
    
    if (newFiles.length > 0) {
        setVirtualFiles(prev => {
            // Merge new files with existing files
            const combined = [...prev];
            newFiles.forEach(nf => {
                const idx = combined.findIndex(f => f.name === nf.name);
                if (idx >= 0) {
                    combined[idx] = { ...nf, status: 'modified' };
                } else {
                    combined.push(nf);
                }
            });
            return combined;
        });
    }
  };

  const handleSendMessage = useCallback(async () => {
    if (!input.trim() || isProcessing) return;

    // 1. Command Parser
    if (input.startsWith('/')) {
      const command = input.slice(1).toUpperCase();
      
      if (command === 'TASKS') {
         setShowTaskDashboard(true);
         setInput('');
         return;
      }

      // Check if command matches an agent ID or Name
      const targetAgent = Object.values(AgentMode).find(
        a => a === command || AGENTS[a].name.toUpperCase().includes(command) || a.includes(command)
      );

      if (targetAgent) {
        handleSwitchAgent(targetAgent);
        setInput('');
        return;
      }
    }

    const currentInput = input;
    setInput('');
    setIsProcessing(true);
    setPendingSwitch(null);

    const userMsg: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: currentInput,
      timestamp: Date.now(),
      agent: activeAgent
    };

    // Update LOCAL history for this agent
    setAgentHistories(prev => ({
      ...prev,
      [activeAgent]: [...prev[activeAgent], userMsg]
    }));

    try {
      // Use the unified AI Service which handles routing to Gemini or Ollama
      const response = await sendMessageToAgent(
          currentInput, 
          agentHistories[activeAgent], 
          activeAgent, 
          toolState, 
          lastAgentResume,
          tasks,
          settings // Pass the full settings object containing provider info
      );

      const agentMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response.text,
        timestamp: Date.now(),
        agent: activeAgent,
        grounding: response.sources ? { urls: response.sources } : undefined
      };

      setAgentHistories(prev => ({
        ...prev,
        [activeAgent]: [...prev[activeAgent], agentMsg]
      }));

      // Task Extraction (Only if PLAN agent)
      if (activeAgent === AgentMode.PLAN) {
         extractTasksFromContent(response.text);
      }

      // File Extraction (Coder, Architect, Test, Deploy)
      if ([AgentMode.CODER, AgentMode.ARCHITECT, AgentMode.TEST, AgentMode.DEPLOY].includes(activeAgent)) {
         extractFilesFromContent(response.text);
      }

      // Handle Orchestrator Suggestion
      if (response.suggestedAgent && response.suggestedAgent !== activeAgent) {
        setPendingSwitch(response.suggestedAgent);
      }

    } catch (error) {
      const errorMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: 'system',
        content: 'ERROR: AGENT CONNECTION INTERRUPTED.',
        timestamp: Date.now(),
        agent: activeAgent,
        isError: true
      };
      setAgentHistories(prev => ({
        ...prev,
        [activeAgent]: [...prev[activeAgent], errorMsg]
      }));
    } finally {
      setIsProcessing(false);
    }
  }, [input, isProcessing, activeAgent, agentHistories, toolState, lastAgentResume, tasks, settings]);

  const handleKeyDownInput = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleUpdateTaskStatus = (taskId: string, status: Task['status']) => {
     setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status } : t));
  };

  if (showBootSequence) {
    return (
      <div className="h-screen w-screen bg-black flex flex-col items-center justify-center font-mono text-nexus-accent overflow-hidden">
        <div className="animate-pulse-fast mb-4">
          <TerminalIcon size={64} />
        </div>
        <h1 className="text-3xl font-bold tracking-[0.5em] mb-2">NEXUSFLOW</h1>
        <div className="flex flex-col items-center gap-1 text-xs text-nexus-dim">
          <p>INITIALIZING PROJECT DIRECTORY...</p>
          <p>LOADING AGENT SUBSYSTEMS...</p>
          <p>ESTABLISHING ORCHESTRATOR LINK...</p>
        </div>
        <div className="w-64 h-1 bg-nexus-900 mt-8 rounded overflow-hidden">
           <div className="h-full bg-nexus-accent animate-[width_2s_ease-in-out_forwards]" style={{ width: '0%' }} />
        </div>
      </div>
    );
  }

  // Derived state for rendering
  const currentMessages = agentHistories[activeAgent];

  return (
    <ConfigurationProvider>
      <div className="h-screen w-screen bg-nexus-900 text-gray-300 font-mono flex overflow-hidden relative">

        {/* Transition Overlay */}
        {transitionTarget && <IncomingTransmission targetAgent={transitionTarget} />}

        {/* CRT Scanline Effect Overlay */}
        <div className={`absolute inset-0 pointer-events-none z-50 scanline-overlay opacity-20 ${!settings.animations ? 'hidden' : ''}`}></div>
        <div className={`absolute inset-0 pointer-events-none z-50 animate-scanline bg-gradient-to-b from-transparent via-nexus-accent/5 to-transparent h-[10%] ${!settings.animations ? 'hidden' : ''}`}></div>

        {/* Task Dashboard Overlay */}
        {showTaskDashboard && (
           <TaskDashboard
              tasks={tasks}
              onClose={() => setShowTaskDashboard(false)}
              onUpdateStatus={handleUpdateTaskStatus}
           />
        )}

        {/* Project Manager (VSCode Bridge) Overlay */}
        {showProjectManager && (
          <ProjectManager
              onClose={() => setShowProjectManager(false)}
              tasks={tasks}
              agentHistories={agentHistories}
              files={virtualFiles}
          />
        )}

        {/* Settings Modal */}
        {showSettings && (
           <SettingsModal
              settings={settings}
              onUpdate={setSettings}
              onClose={() => setShowSettings(false)}
           />
        )}

        {/* Left Sidebar: System Stats & Grid */}
        <div className="w-80 bg-nexus-900 border-r border-nexus-border flex flex-col z-10 shadow-xl">
          <div className={`p-4 border-b border-nexus-border flex items-center gap-3 transition-all duration-300 ${pendingSwitch ? 'bg-nexus-900' : 'bg-nexus-800/30'}`}>
            {pendingSwitch ? (
              <>
                 <div className={`p-1.5 rounded-sm border animate-pulse ${AGENTS[pendingSwitch].color.replace('text-', 'border-')} bg-opacity-10`}>
                    <ArrowRightLeft size={18} className={AGENTS[pendingSwitch].color} />
                 </div>
                 <div className="flex-1 min-w-0">
                    <h1 className={`font-bold text-xs tracking-wider mb-0.5 ${AGENTS[pendingSwitch].color} truncate`}>
                        SUGGESTION: {AGENTS[pendingSwitch].id}
                    </h1>
                     <div className="flex items-center gap-2">
                        <button
                            onClick={() => handleSwitchAgent(pendingSwitch)}
                            className="text-[10px] bg-nexus-800 hover:bg-nexus-700 text-nexus-accent px-2 py-0.5 rounded border border-nexus-border hover:border-nexus-accent transition-colors flex items-center gap-1"
                        >
                            <Check size={10} /> ACCEPT
                        </button>
                        <button
                            onClick={() => setPendingSwitch(null)}
                            className="text-[10px] text-nexus-dim hover:text-gray-300 px-1 py-0.5 transition-colors"
                        >
                            DISMISS
                        </button>
                    </div>
                 </div>
              </>
            ) : (
              <>
                <div className="bg-nexus-accent text-black p-1 rounded-sm">
                  <FolderOpen size={20} />
                </div>
                <div className="flex-1">
                  <h1 className="font-bold text-white tracking-wider text-sm">PROJECT ROOT</h1>
                  <div className="flex items-center justify-between">
                      <div className="flex items-center gap-1 text-[10px] text-nexus-accent">
                          <span className="w-1.5 h-1.5 bg-nexus-accent rounded-full animate-pulse"></span>
                          ACTIVE
                      </div>
                      {tasks.length > 0 && (
                          <button
                              onClick={() => setShowTaskDashboard(true)}
                              className="text-[9px] bg-nexus-800 px-1.5 rounded border border-nexus-border hover:text-white transition-colors flex items-center gap-1"
                          >
                              <ListTodo size={9} />
                              {tasks.filter(t => t.status !== 'done').length} TASKS
                          </button>
                      )}
                  </div>
                </div>
              </>
            )}
          </div>

          <div className="flex-1 overflow-y-auto custom-scrollbar">
            <AgentGrid activeAgent={activeAgent} />
          </div>

          <div className="h-[400px] border-t border-nexus-border flex flex-col bg-nexus-900">
             <div className="flex border-b border-nexus-border">
                <button
                  onClick={() => setSidebarTab('telemetry')}
                  className={`flex-1 py-2 text-[10px] font-mono font-bold uppercase tracking-wider transition-colors ${
                    sidebarTab === 'telemetry'
                      ? 'bg-nexus-800/50 text-nexus-accent border-b-2 border-nexus-accent'
                      : 'bg-nexus-900 text-gray-500 hover:bg-nexus-800/50 hover:text-gray-300'
                  }`}
                >
                  Telemetry
                </button>
                <button
                  onClick={() => setSidebarTab('tools')}
                  className={`flex-1 py-2 text-[10px] font-mono font-bold uppercase tracking-wider transition-colors ${
                    sidebarTab === 'tools'
                      ? 'bg-nexus-800/50 text-nexus-accent border-b-2 border-nexus-accent'
                      : 'bg-nexus-900 text-gray-500 hover:bg-nexus-800/50 hover:text-gray-300'
                  }`}
                >
                  Tools
                </button>
             </div>
             <div className="flex-1 overflow-y-auto custom-scrollbar relative">
                {sidebarTab === 'telemetry'
                  ? <SystemMonitor />
                  : <ToolsPanel toolState={toolState} setToolState={setToolState} />
                }
             </div>
          </div>
        </div>

        {/* Main Terminal Area */}
        <div className="flex-1 flex flex-col bg-[#0a0a0a] z-10 relative" onClick={handleContainerClick}>

          {/* Header Bar */}
          <div className="h-12 border-b border-nexus-border flex items-center justify-between px-6 bg-nexus-900/80 backdrop-blur">
            <div className="flex items-center gap-4">
               <span className={`text-xs font-bold px-2 py-1 rounded ${AGENTS[activeAgent].color.replace('text-', 'bg-').replace('400','900').replace('500','900')} bg-opacity-20 border border-opacity-30 ${AGENTS[activeAgent].color.replace('text-', 'border-')}`}>
                  <span className="opacity-50">./agents/</span>{activeAgent}
               </span>
               <span className="text-xs text-nexus-dim">/// {AGENTS[activeAgent].description}</span>
            </div>

            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 text-nexus-dim text-xs">
                 <ShieldCheck size={14} className="text-nexus-accent" />
                 <span>SECURE ENCLAVE</span>
              </div>

              {/* VSCode Bridge Button (Always visible for demo purposes, but logically highlighted for Ollama) */}
              <button
                  onClick={() => setShowProjectManager(true)}
                  className={`transition-colors p-1.5 rounded hover:bg-nexus-800 border border-transparent hover:border-blue-900/50 flex items-center gap-2 ${virtualFiles.length > INITIAL_FILES.length ? 'text-nexus-accent animate-pulse' : 'text-blue-400 hover:text-blue-300'}`}
                  title="VSCode Bridge (Local File System)"
                >
                <Laptop size={16} />
                <span className="text-xs font-bold hidden md:inline">VSCODE BRIDGE</span>
              </button>

              <button
                onClick={() => setShowSettings(true)}
                className="text-nexus-dim hover:text-nexus-accent transition-colors p-1 rounded hover:bg-nexus-800"
                title="Settings"
              >
                <SettingsIcon size={16} />
              </button>
            </div>
          </div>

          {/* Messages Scroll Area */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar relative">

            {currentMessages.length === 0 && (
               <div className="flex flex-col items-center justify-center h-full text-nexus-dim opacity-50">
                  <FolderOpen size={48} />
                  <p className="mt-4 font-mono text-sm">CHANNEL EMPTY</p>
                  <p className="text-xs">Type to initialize {AGENTS[activeAgent].name}</p>
               </div>
            )}

            {currentMessages.map((msg) => {
               // Safe Icon Rendering using Map
               const AgentIcon = AGENT_ICONS[AGENTS[msg.agent].icon] || MessageSquare;

               const isUser = msg.role === 'user';
               const isSystem = msg.role === 'system';

               if (isSystem) {
                  return (
                      <div key={msg.id} className="flex justify-center my-4 animate-fade-in">
                          <span className={`text-xs font-mono px-3 py-1 border ${msg.isError ? 'border-red-900 text-red-500 bg-red-900/10' : 'border-nexus-border text-nexus-dim bg-nexus-800/50'}`}>
                               {msg.isError && <AlertTriangle size={12} className="inline mr-2 mb-0.5"/>}
                               {msg.content}
                          </span>
                      </div>
                  )
               }

               return (
                  <div key={msg.id} className={`flex gap-4 ${isUser ? 'flex-row-reverse' : 'flex-row'} group animate-fade-in`}>
                      <div className={`flex-shrink-0 w-8 h-8 rounded flex items-center justify-center ${isUser ? 'bg-nexus-dim text-white' : `${AGENTS[msg.agent].color} bg-nexus-800 border border-nexus-border`}`}>
                          {isUser ? <User size={16} /> : <AgentIcon size={16} />}
                      </div>

                      <div className={`max-w-[80%] space-y-1`}>
                          <div className={`flex items-center gap-2 text-[10px] uppercase ${isUser ? 'justify-end text-nexus-dim' : AGENTS[msg.agent].color}`}>
                              {isUser ? 'YOU' : msg.agent} <span className="opacity-50">{new Date(msg.timestamp).toLocaleTimeString()}</span>
                          </div>
                          <div className={`p-4 rounded-sm text-sm leading-relaxed whitespace-pre-wrap font-mono shadow-lg
                              ${isUser
                                  ? 'bg-nexus-800 text-gray-200 border border-nexus-border'
                                  : 'bg-black text-gray-300 border-l-2 border-nexus-border ' + AGENTS[msg.agent].color.replace('text-', 'border-')
                              }`}>
                              {msg.content}

                              {/* Render Grounding Sources if present */}
                              {msg.grounding && msg.grounding.urls.length > 0 && (
                                <div className="mt-3 pt-3 border-t border-nexus-border/50">
                                  <div className="text-[10px] text-nexus-dim mb-1 flex items-center gap-1">
                                    <Globe size={10} />
                                    <span>VERIFIED SOURCES</span>
                                  </div>
                                  <div className="flex flex-wrap gap-2">
                                    {msg.grounding.urls.map((url, idx) => (
                                      <a
                                        key={idx}
                                        href={url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="flex items-center gap-1 px-2 py-1 bg-nexus-900/80 border border-nexus-border hover:border-nexus-accent text-[10px] text-nexus-accent rounded transition-colors truncate max-w-[200px]"
                                      >
                                        <ExternalLink size={8} />
                                        {new URL(url).hostname}
                                      </a>
                                    ))}
                                  </div>
                                </div>
                              )}
                          </div>
                      </div>
                  </div>
               );
            })}
            {isProcessing && (
              <div className="flex gap-4 animate-pulse">
                   <div className={`w-8 h-8 rounded bg-nexus-800 border border-nexus-border flex items-center justify-center ${AGENTS[activeAgent].color}`}>
                       <Loader2 size={16} className="animate-spin" />
                   </div>
                   <div className="flex items-center text-xs text-nexus-dim font-mono">
                      {activeAgent} IS THINKING ({settings.aiProvider === 'ollama' ? 'LOCAL' : 'CLOUD'})...
                   </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Input Area */}
          <div className="p-4 bg-nexus-900 border-t border-nexus-border z-50">
              <div className="flex items-center gap-2 bg-black border border-nexus-border p-3 rounded-sm focus-within:border-nexus-accent transition-colors shadow-[0_0_15px_rgba(0,0,0,0.5)]">
                  <span className={`${AGENTS[activeAgent].color} font-bold text-lg`}>›</span>
                  <input
                      ref={inputRef}
                      type="text"
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={handleKeyDownInput}
                      placeholder={`/${activeAgent.toLowerCase()}, /tasks or message...`}
                      className="flex-1 bg-transparent border-none outline-none text-gray-200 font-mono placeholder-gray-700"
                      autoComplete="off"
                      disabled={!!transitionTarget}
                  />
                  <div className="flex items-center gap-2">
                       <div className="hidden md:flex items-center gap-1 px-2 py-1 bg-nexus-800 rounded text-[10px] text-gray-500 border border-nexus-border">
                          <Command size={10} />
                          <span>ENTER</span>
                       </div>
                      <button
                          onClick={handleSendMessage}
                          disabled={isProcessing || !!transitionTarget}
                          className={`p-2 rounded hover:bg-nexus-800 transition-colors ${isProcessing ? 'opacity-50 cursor-not-allowed' : 'text-nexus-accent'}`}
                      >
                          <Send size={18} />
                      </button>
                  </div>
              </div>
          </div>

        </div>
      </div>
    </ConfigurationProvider>
  );
}
