import React from 'react';
import { 
  ShieldCheck, 
  Laptop, 
  Settings as SettingsIcon,
  AlertTriangle,
  CheckCircle,
  XCircle
} from 'lucide-react';
import { AGENTS, AgentMode, VirtualFile } from '../types';
import { useAgenticSystems } from '../hooks/useAgenticSystems';
import { AgentPhase, PHASE_CONFIGS } from '../src/agentic';

const INITIAL_FILES: VirtualFile[] = [
  { name: 'package.json', content: '{\n  "name": "nexus-project",\n  "version": "1.0.0"\n}', language: 'json', status: 'unmodified' },
  { name: 'README.md', content: '# Nexus Project\nGenerated by NexusFlow Agents', language: 'markdown', status: 'unmodified' },
  { name: 'src/index.ts', content: 'console.log("Nexus Core Online");', language: 'typescript', status: 'unmodified' },
];

const getPhaseColor = (phase: AgentPhase): string => {
  const colors: Record<AgentPhase, string> = {
    P: 'bg-purple-900/50 border-purple-500/50 text-purple-400',
    R: 'bg-blue-900/50 border-blue-500/50 text-blue-400',
    I: 'bg-green-900/50 border-green-500/50 text-green-400',
    D: 'bg-orange-900/50 border-orange-500/50 text-orange-400',
    E: 'bg-cyan-900/50 border-cyan-500/50 text-cyan-400',
    S: 'bg-red-900/50 border-red-500/50 text-red-400'
  };
  return colors[phase] || 'bg-gray-900/50 border-gray-500/50 text-gray-400';
};

interface HeaderProps {
  activeAgent: AgentMode;
  virtualFiles: VirtualFile[];
  onShowSettings: () => void;
  onShowProjectManager: () => void;
}

export const Header: React.FC<HeaderProps> = ({
  activeAgent,
  virtualFiles,
  onShowSettings,
  onShowProjectManager
}) => {
  // Agentic systems
  const [agenticState] = useAgenticSystems();
  const { agentStates, isHalted, lastGateStatus, driftEvents } = agenticState;

  // Get current agent's phase
  const currentAgentState = agentStates.get(activeAgent);
  const currentPhase = (currentAgentState?.phase || 'P') as keyof typeof PHASE_CONFIGS;
  const phaseConfig = PHASE_CONFIGS[currentPhase];

  return (
    <div className="h-12 border-b border-nexus-border flex items-center justify-between px-6 bg-nexus-900/80 backdrop-blur">
      <div className="flex items-center gap-4">
         <span className={`text-xs font-bold px-2 py-1 rounded ${AGENTS[activeAgent].color.replace('text-', 'bg-').replace('400','900').replace('500','900')} bg-opacity-20 border border-opacity-30 ${AGENTS[activeAgent].color.replace('text-', 'border-')}`}>
            <span className="opacity-50">./agents/</span>{activeAgent}
         </span>
         <span className="text-xs text-nexus-dim">/// {AGENTS[activeAgent].description}</span>
         
         {/* Phase Indicator */}
         <div className={`flex items-center gap-1 px-2 py-0.5 rounded border text-[10px] font-mono ${getPhaseColor(currentPhase)}`}>
            <span className="opacity-70">PHASE:</span>
            <span className="font-bold">{currentPhase}</span>
            <span className="opacity-70">({phaseConfig.name})</span>
         </div>
      </div>

      <div className="flex items-center gap-4">
        {/* Gate Status */}
        {lastGateStatus && (
          <div className={`flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-mono ${
            lastGateStatus === 'PASS' 
              ? 'bg-green-900/50 border border-green-500/50 text-green-400'
              : 'bg-red-900/50 border border-red-500/50 text-red-400'
          }`}>
            {lastGateStatus === 'PASS' ? <CheckCircle size={10} /> : <XCircle size={10} />}
            <span>GATE: {lastGateStatus}</span>
          </div>
        )}

        {/* Drift Warning */}
        {driftEvents.length > 0 && (
          <div className="flex items-center gap-1 px-2 py-0.5 rounded bg-yellow-900/50 border border-yellow-500/50 text-yellow-400 text-[10px] font-mono">
            <AlertTriangle size={10} />
            <span>DRIFT: {driftEvents.length}</span>
          </div>
        )}

        {/* System Halt */}
        {isHalted && (
          <div className="flex items-center gap-1 px-2 py-0.5 rounded bg-red-900/50 border border-red-500/50 text-red-400 text-[10px] font-mono animate-pulse">
            <XCircle size={10} />
            <span>HALTED</span>
          </div>
        )}

        <div className="flex items-center gap-2 text-nexus-dim text-xs">
           <ShieldCheck size={14} className={isHalted ? 'text-red-500' : 'text-nexus-accent'} />
           <span>{isHalted ? 'LOCKDOWN' : 'SECURE ENCLAVE'}</span>
        </div>

        {/* VSCode Bridge Button */}
        <button
            onClick={onShowProjectManager}
            className={`transition-colors p-1.5 rounded hover:bg-nexus-800 border border-transparent hover:border-blue-900/50 flex items-center gap-2 ${virtualFiles.length > INITIAL_FILES.length ? 'text-nexus-accent animate-pulse' : 'text-blue-400 hover:text-blue-300'}`}
            title="VSCode Bridge (Local File System)"
          >
          <Laptop size={16} />
          <span className="text-xs font-bold hidden md:inline">VSCODE BRIDGE</span>
        </button>

        <button
          onClick={onShowSettings}
          className="text-nexus-dim hover:text-nexus-accent transition-colors p-1 rounded hover:bg-nexus-800"
          title="Settings"
        >
          <SettingsIcon size={16} />
        </button>
      </div>
    </div>
  );
};
