import React from 'react';
import { 
  ShieldCheck, 
  Laptop, 
  Settings as SettingsIcon 
} from 'lucide-react';
import { AGENTS, AgentMode, VirtualFile } from '../types';

const INITIAL_FILES: VirtualFile[] = [
  { name: 'package.json', content: '{\n  "name": "nexus-project",\n  "version": "1.0.0"\n}', language: 'json', status: 'unmodified' },
  { name: 'README.md', content: '# Nexus Project\nGenerated by NexusFlow Agents', language: 'markdown', status: 'unmodified' },
  { name: 'src/index.ts', content: 'console.log("Nexus Core Online");', language: 'typescript', status: 'unmodified' },
];

interface HeaderProps {
  activeAgent: AgentMode;
  virtualFiles: VirtualFile[];
  onShowSettings: () => void;
  onShowProjectManager: () => void;
}

export const Header: React.FC<HeaderProps> = ({
  activeAgent,
  virtualFiles,
  onShowSettings,
  onShowProjectManager
}) => {
  return (
    <div className="h-12 border-b border-nexus-border flex items-center justify-between px-6 bg-nexus-900/80 backdrop-blur">
      <div className="flex items-center gap-4">
         <span className={`text-xs font-bold px-2 py-1 rounded ${AGENTS[activeAgent].color.replace('text-', 'bg-').replace('400','900').replace('500','900')} bg-opacity-20 border border-opacity-30 ${AGENTS[activeAgent].color.replace('text-', 'border-')}`}>
            <span className="opacity-50">./agents/</span>{activeAgent}
         </span>
         <span className="text-xs text-nexus-dim">/// {AGENTS[activeAgent].description}</span>
      </div>

      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2 text-nexus-dim text-xs">
           <ShieldCheck size={14} className="text-nexus-accent" />
           <span>SECURE ENCLAVE</span>
        </div>

        {/* VSCode Bridge Button */}
        <button
            onClick={onShowProjectManager}
            className={`transition-colors p-1.5 rounded hover:bg-nexus-800 border border-transparent hover:border-blue-900/50 flex items-center gap-2 ${virtualFiles.length > INITIAL_FILES.length ? 'text-nexus-accent animate-pulse' : 'text-blue-400 hover:text-blue-300'}`}
            title="VSCode Bridge (Local File System)"
          >
          <Laptop size={16} />
          <span className="text-xs font-bold hidden md:inline">VSCODE BRIDGE</span>
        </button>

        <button
          onClick={onShowSettings}
          className="text-nexus-dim hover:text-nexus-accent transition-colors p-1 rounded hover:bg-nexus-800"
          title="Settings"
        >
          <SettingsIcon size={16} />
        </button>
      </div>
    </div>
  );
};
